import { Lesson } from '.';
import { OnBoard } from '.';
import { FlightTypeCode } from '.';
import { TOLData } from '.';
import { BillingStatusCode } from '.';
import { RiskAssessment } from '.';
import { BaseEntity } from '.';
import { FlightStatusCode } from '.';
import { FlightStateCode } from '.';
import { FlightPurposeCode } from '.';
import { ReFuel } from '.';
export declare class Flight extends BaseEntity {
    name: string;
    description: string;
    flightNumber: number;
    flightString: string;
    destination: string;
    accountId: string;
    airplaneId: string;
    onBoard: OnBoard;
    type: FlightTypeCode;
    status: FlightStatusCode;
    state: FlightStateCode;
    purpose: FlightPurposeCode;
    purposeOt: string;
    takeoff: TOLData;
    landing: TOLData;
    wbConfig: string;
    wbManual: string;
    hasCompetency: boolean;
    hasFlightPlan: boolean;
    preFlightNotes: string;
    operationNotes: string;
    attendingTime: string;
    boardingTime: string;
    pilotCertificationCheck: number;
    billingStatus: BillingStatusCode;
    fuelStatus: ReFuel;
    oilStatus: ReFuel;
    lesson: Lesson;
    riskAssessment: RiskAssessment;
}
