import { MessageConfirmsEndPoint } from '.';
import { UsersEndPoint } from '.';
import { AccountsEndPoint } from '.';
import { AuditLogsEndPoint } from '.';
import { BookingsEndPoint } from '.';
import { DocumentsEndPoint } from '.';
import { AirplanesEndPoint } from '.';
import { ContactsEndPoint } from '.';
import { CreditsEndPoint } from '.';
import { CertificatesEndPoint } from '.';
import { FlightTicketsEndPoint } from '.';
import { FlightsEndPoint } from '.';
import { UserEndPoint } from '.';
import { CampaignsEndPoint } from '.';
import { LeadsEndPoint } from '.';
import { MaintenancesEndPoint } from '.';
import { SystemMessagesEndPoint } from '.';
export declare const Services: (typeof CampaignsEndPoint | typeof LeadsEndPoint | typeof MaintenancesEndPoint | typeof SystemMessagesEndPoint | typeof UserEndPoint | typeof AccountsEndPoint | typeof AuditLogsEndPoint | typeof BookingsEndPoint | typeof DocumentsEndPoint | typeof MessageConfirmsEndPoint | typeof UsersEndPoint | typeof AirplanesEndPoint | typeof ContactsEndPoint | typeof CreditsEndPoint | typeof CertificatesEndPoint | typeof FlightTicketsEndPoint | typeof FlightsEndPoint)[];
